INSERT INTO users (name, age) VALUES ('Abe', 17);
INSERT INTO users (name, age) VALUES ('Al', 85);
INSERT INTO users (name, age) VALUES ('Joe', 52);
INSERT INTO users (name, age) VALUES ('Pat', 35);
INSERT INTO users (name, age) VALUES ('Sam', 15);
INSERT INTO users (name, age) VALUES ('Jim', 90);
INSERT INTO users (name, age) VALUES ('Alberta', 65);
INSERT INTO users (name, age) VALUES ('Queenie', 42);
INSERT INTO users (name, age) VALUES ('Mike', 35);
INSERT INTO users (name, age) VALUES ('Josh', 42);
INSERT INTO users (name, age) VALUES ('George', 55);
INSERT INTO users (name, age) VALUES ('Sammie', 44);
INSERT INTO users (name, age) VALUES ('Corgie', 21);
INSERT INTO users (name, age) VALUES ('Alice', 65);
INSERT INTO users (name, age) VALUES ('Lenny', 74);
INSERT INTO users (name, age) VALUES ('Allie', 41);
INSERT INTO users (name, age) VALUES ('Henry', 54);
INSERT INTO users (name, age) VALUES ('Josephine', 14);
INSERT INTO users (name, age) VALUES ('A', 42);
INSERT INTO users (name, age) VALUES ('Peter', 65);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Stuff', 'Dumb Ideas', 6000, 'August 16, 2020', 'December 31, 2020');

INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 2, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 5, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 3, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400, 4, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 5, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 9, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 7, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 7, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 7, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 9, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 9, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 7, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 7, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 7, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 9, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 7, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 7, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 7, 5);

